Repository AOT-Technologies/forms-flow-ai-micro-front-ends, pull requests merged in 2025-09, with the labels that each got.

#778 FWF-4969:[feature] - Bundle Task Details Page Added
  forms-flow-review/package-lock.json
  forms-flow-review/package.json
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/taskActions.ts
  forms-flow-review/src/api/endpoints.ts
  forms-flow-review/src/api/services/bpmTaskServices.ts
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/components/BundleTaskForm.tsx
  forms-flow-review/src/reducers/taskReducer.ts
Labels: Review effort 3/5

#780 FWF-5151 : [BugFix] Analyze-submission date display fix
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 2/5

#782 FWF-5241 : [BugFix] Column sort issue fixed in analyze-submission listing
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 2/5

#783 FWF-5170[bugfix]custom header issue in roles page
  forms-flow-admin/src/components/roles/roles.tsx
  forms-flow-review/src/api/services/filterServices.ts
Labels: Review effort 2/5

#773 feature/fwf-4841:Added sorting for columns in review table
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
  forms-flow-review/src/components/AttributeFilterModal/ParametersTab.tsx
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
  forms-flow-review/src/components/TaskList/TaskList.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-review/src/components/constants/taskConstants.ts
  forms-flow-review/src/helper/tableHelper.ts
  forms-flow-review/src/helper/taskHelper.ts
  forms-flow-submissions/src/constants/variables.ts
Labels: Review effort 3/5

#784 updated react bootstrap version to 2.10.6
  forms-flow-admin/package-lock.json
  forms-flow-admin/package.json
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-components/src/components/CustomComponents/Pills.tsx
  forms-flow-nav/package-lock.json
  forms-flow-nav/package.json
  forms-flow-review/package-lock.json
  forms-flow-review/package.json
  forms-flow-service/package-lock.json
  forms-flow-submissions/package-lock.json
  forms-flow-submissions/package.json
  forms-flow-theme/scss/_button.scss
Labels: Review effort 2/5

#788 FWF-5312 [upgrade] ui fix for pills and tabs
  forms-flow-components/src/components/CustomComponents/Pills.tsx
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/_modal.scss
  forms-flow-theme/scss/external/formio.scss
Labels: Review effort 2/5

#787 FWF-5148 : [Modified] Added placeholder for date and time searches in collapsible search
  forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 2/5

#794 bugfix/fwf-5262:Fixed showing blank entries in submissiom table
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
  forms-flow-components/src/components/CustomComponents/SortableHeadder.tsx
  forms-flow-review/src/components/FormSelectionModal.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 2/5

#796 FWF-5303 : [BugFix] Fixed analyze-submission filter back to default issue
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/actions/actionConstants.ts
  forms-flow-submissions/src/actions/analyzeSubmissionActions.ts
  forms-flow-submissions/src/reducers/analizeSubmissionReducer.ts
Labels: Review effort 2/5

#797 bufgix/fwf-5167:Fixed Advanced components rendering and searching
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
  forms-flow-components/src/components/CustomComponents/InputDropdown.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/AttributeFilterModal/ParametersTab.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 3/5

#799 FWF-5311[bugfix]expression builder UI issues
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/_modal.scss
Labels: Review effort 2/5

#805 FWF-5333 [update] style fix for form import
  forms-flow-theme/scss/fileUpload.scss
Labels: Review effort 1/5

#806 FWF-5344 [Upgrade] updated styling and ovverride style for template
  forms-flow-components/src/components/CustomComponents/InputDropdown.tsx
  forms-flow-theme/scss/_button.scss
Labels: Review effort 2/5

#808 Version Update and Google Notification for v8-develop.
  .github/workflows/pr-notification.yml
  VERSION
  forms-flow-admin/package-lock.json
  forms-flow-admin/package.json
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-integration/package-lock.json
  forms-flow-integration/package.json
  forms-flow-nav/package-lock.json
  forms-flow-nav/package.json
  forms-flow-review/package-lock.json
  forms-flow-review/package.json
  forms-flow-service/package-lock.json
  forms-flow-service/package.json
  forms-flow-submissions/package-lock.json
  forms-flow-submissions/package.json
  forms-flow-theme/package-lock.json
  forms-flow-theme/package.json
Labels: Review effort 1/5

#812 FWF-5354 [bugfix] updated the route issue from bundle task and submis…
  forms-flow-components/src/components/CustomComponents/SubmissionHistoryWithViewButton.tsx
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-review/src/api/services/formatterService.ts
  forms-flow-review/src/components/TaskHistory.tsx
  forms-flow-submissions/src/components/AnalyzeSubmissionView.tsx
Labels: Review effort 2/5

#813 FWF-5346[feature] - progress bar for v8
  forms-flow-components/src/components/CustomComponents/ImportModal.tsx
  forms-flow-components/src/components/CustomComponents/ProgressBar.tsx
  forms-flow-theme/scss/fileUpload.scss
  forms-flow-theme/scss/v8-scss/_theme.scss
Labels: Review effort 2/5

#814 feature/fwf-5210-5211: Added button and icon-only button
  forms-flow-components/src/components/CustomComponents/CustomButton.tsx
  forms-flow-components/src/components/index.ts
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/v8-scss/_button.scss
Labels: Review effort 2/5

#815 feature/fwf-5214:Added search input component
  forms-flow-components/src/components/CustomComponents/Search.tsx
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/v8-scss/_search.scss
Labels: Review effort 2/5

#820 FWF-5368 [bugfix] updated payload structure for checkbox
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/AttributeFilterModal/ParametersTab.tsx
Labels: Review effort 2/5

#822 Feature/fwf 5374 v 8 create storybook integration
  forms-flow-components/.storybook/main.js
  forms-flow-components/.storybook/preview.css
  forms-flow-components/.storybook/preview.ts
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-components/src/components/CustomComponents/CustomButton.tsx
  forms-flow-components/src/components/Stories/CustomButton.stories.tsx
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/v8-scss/_button.scss
Labels: Review effort 3/5

#824 FWF-5366 [bugfix] updated logic of form variable selection
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
Labels: Review effort 2/5

#827 Feature/fwf 5218 UI modal
  forms-flow-admin/src/declarations.d.ts
  forms-flow-components/src/components/CustomComponents/PromptModal.tsx
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-components/src/components/index.ts
  forms-flow-review/src/declarations.d.ts
  forms-flow-theme/package-lock.json
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/v8-scss/_modal.scss
Labels: Review effort 2/5

#830 Feature/fwf 5207 UI checkbox
  forms-flow-components/src/components/CustomComponents/Radio.tsx
  forms-flow-components/src/components/Stories/CustomRadioButton.stories.tsx
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/v8-scss/_radio.scss
Labels: Review effort 3/5

#826 FWF-5217[feature] v8 button dropdown
  forms-flow-components/src/components/CustomComponents/CustomDropdownButton.tsx
  forms-flow-components/src/components/index.ts
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/v8-scss/_dropdownButton.scss
Labels: Review effort 2/5

#834 FWF-5349 : [BugFix] Updated and overrided styles for ui fixes
  forms-flow-theme/scss/bpmn.scss
  forms-flow-theme/scss/external/formio.scss
Labels: Review effort 2/5

#828 Feature/fwf 5205 select dropdown
  forms-flow-components/src/components/CustomComponents/SelectDropdown.tsx
  forms-flow-components/src/components/index.ts
  forms-flow-theme/scss/_card.scss
  forms-flow-theme/scss/_typography.scss
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/v8-scss/_selectDropdown.scss
Labels: Review effort 3/5

#829 V8 feature/fwf 5338 common mixins and layouts
  forms-flow-theme/scss/_table.scss
  forms-flow-theme/scss/v8-scss/_mixins.scss
  forms-flow-theme/scss/v8-scss/_theme.scss
Labels: Review effort 3/5

#821 [SYNC] Syncing develop to v8-develop
  forms-flow-admin/src/components/users/users.tsx
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
  forms-flow-components/src/components/CustomComponents/InputDropdown.tsx
  forms-flow-components/src/components/CustomComponents/SubmissionHistoryWithViewButton.tsx
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/api/services/formatterService.ts
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/AttributeFilterModal/ParametersTab.tsx
  forms-flow-review/src/components/TaskHistory.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/components/AnalyzeSubmissionView.tsx
  forms-flow-theme/scss/_button.scss
  forms-flow-theme/scss/bpmn.scss
  forms-flow-theme/scss/external/formio.scss
  forms-flow-theme/scss/fileUpload.scss
Labels: Review effort 3/5

#836 feature/fwf-5206:Added multiselectcomponent
  forms-flow-components/src/components/CustomComponents/DropdownMultiselect.tsx
  forms-flow-components/src/components/CustomComponents/MultiSelect.tsx
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/v8-scss/_dropdownMultiselect.scss
Labels: Review effort 3/5

#825 FWF-5346[feature] - Navbar changes for v8
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-nav/src/sidenav/MenuComponent.jsx
  forms-flow-nav/src/sidenav/Sidebar.jsx
  forms-flow-nav/src/sidenav/Sidebar.scss
  forms-flow-theme/scss/_mixins.scss
  forms-flow-theme/scss/_theme.scss
  forms-flow-theme/scss/v8-scss/_theme.scss
Labels: Review effort 3/5
