Repository AOT-Technologies/forms-flow-ai-micro-front-ends, pull requests merged in 2025-06, with the labels that each got.

#584 Bugfix/FWF 3740 updated missing data testid in microfrontend
  forms-flow-components/src/components/CustomComponents/BuildModal.tsx
  forms-flow-components/src/components/CustomComponents/Button.tsx
  forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx
  forms-flow-components/src/components/CustomComponents/CustomInfo.tsx
  forms-flow-components/src/components/CustomComponents/FormBuilderModal.tsx
  forms-flow-components/src/components/CustomComponents/ImportModal.tsx
  forms-flow-components/src/components/CustomComponents/SortableHeadder.tsx
  forms-flow-components/src/components/CustomComponents/TableFooter.tsx
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-nav/src/root.component.js
  forms-flow-nav/src/sidenav/MenuComponent.jsx
  forms-flow-nav/src/sidenav/Sidebar.jsx
Labels: Review effort 3/5

#585 FWF-4671:[Feature] - Skeleton Loader SCSS updates.
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-components/src/components/SkeletonLoader/TableSkeletonLoader.tsx
  forms-flow-components/src/components/index.ts
  forms-flow-theme/scss/_skeletonLoader.scss
  forms-flow-theme/scss/index.scss
Labels: Review effort 2/5

#583 Feature/fwf 4550 application list API and UI in mf
  forms-flow-nav/src/Navbar.jsx
  forms-flow-nav/src/sidenav/Sidebar.jsx
  forms-flow-submissions/package-lock.json
  forms-flow-submissions/package.json
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/Routes/SubmissionsListing/List.tsx
  forms-flow-submissions/src/actions/actionConstants.ts
  forms-flow-submissions/src/actions/analyzeSubmissionActions.ts
  forms-flow-submissions/src/api/config.ts
  forms-flow-submissions/src/api/endpoints.ts
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
  forms-flow-submissions/src/constants/actionConstants.ts
  forms-flow-submissions/src/declarations.d.ts
  forms-flow-submissions/src/helper/helper.ts
  forms-flow-submissions/src/index.tsx
  forms-flow-submissions/src/react-query-client.ts
  forms-flow-submissions/src/reducers/analizeSubmissionReducer.ts
  forms-flow-submissions/src/reducers/index.ts
  forms-flow-submissions/src/root.component.tsx
  forms-flow-submissions/src/services/StoreServices.ts
  forms-flow-submissions/src/types/submissions.ts
Labels: Review effort 4/5

#590 modified/FWF-4171 [modified] override style of wizard cancel button
  forms-flow-theme/scss/external/formio.scss
Labels: Review effort 1/5

#595 FWF-4647: [BugFix] fixed processVariable issue for filters with no form
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
  forms-flow-review/src/components/TaskList/AttributeFilterDropdown.tsx
Labels: Review effort 2/5

#596 Feature/FWF-4673-UI updation in role management modal
  forms-flow-admin/src/components/roles/permissionTree.tsx
  forms-flow-admin/src/components/roles/roles.scss
  forms-flow-admin/src/components/roles/roles.tsx
  forms-flow-admin/src/declarations.d.ts
  forms-flow-theme/scss/_forms.scss
Labels: Review effort 4/5

#597 FWF-4647: [Modified] Added All tasks data, if no filter present, removed no selected filter text
  forms-flow-review/src/components/TaskList/TaskFilterDropdown.tsx
  forms-flow-review/src/components/TaskList/TaskList.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-review/src/constants/allTasksPayload.ts
Labels: Review effort 4/5

#602 FWF-4814: [BugFix] filter re-order fixes, roles listing fix, dueDate removed, form variable icon added
  forms-flow-components/src/components/CustomComponents/DragandDropSort.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/ReorderTaskFilterModal.tsx
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
  forms-flow-review/src/components/TaskList/TaskFilterDropdown.tsx
  forms-flow-review/src/components/TaskList/TaskList.tsx
  forms-flow-review/src/constants/allTasksPayload.ts
  forms-flow-theme/scss/_modal.scss
  forms-flow-theme/scss/inputBox.scss
Labels: Review effort 4/5

#598 Bugfix/FWF-4263-scroll bar added in variable selection modal
  forms-flow-theme/scss/_modal.scss
Labels: Review effort 1/5

#601 modified/FWF-4784-permission [modified] updated permission
  forms-flow-admin/src/index.tsx
  forms-flow-components/src/__test__/dateFilter.test.tsx
  forms-flow-components/src/__test__/historyModal.test.tsx
  forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
  forms-flow-nav/src/sidenav/Sidebar.jsx
  forms-flow-submissions/src/components/AccessDenied/AccessDenied.js
  forms-flow-submissions/src/components/AccessDenied/accessDenied.scss
  forms-flow-submissions/src/components/AccessDenied/index.js
  forms-flow-submissions/src/index.tsx
Labels: Review effort 4/5

#606 Hotfix for specific role not listing mf
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-review/src/index.tsx
Labels: Review effort 2/5

#608 FWF-4550:[Feature] Removed Header to get default header.
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
Labels: Review effort 1/5

#610 FWF-4826 [fix] fixed reviewer action payload to bpmn
  forms-flow-review/src/Routes/TaskDetails.tsx
Labels: Review effort 2/5

#612 FWF-4550:[Bugfix] - Updated Env Variable name in config.
  forms-flow-submissions/src/api/config.ts
Labels: Review effort 1/5

#609 FWF-4815 [feature] added functionality of tasklist row based on the displayLinesCount
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-review/src/helper/tableHelper.ts
  forms-flow-theme/scss/_table.scss
Labels: Review effort 2/5

#615 feature/fwf-4786: Updated reviewer screen with permission matrix
  forms-flow-components/src/components/CustomComponents/AssignUser.tsx
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-review/src/components/Assigne/Assigne.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/TaskFilterModal/SaveFilterTab.tsx
  forms-flow-review/src/components/TaskList/TaskFilterDropdown.tsx
  forms-flow-review/src/components/TaskList/TaskList.tsx
  forms-flow-review/src/helper/permissions.ts
Labels: Review effort 3/5

#616 FWF-4820: [BugFix] filter share icon conditions updated
  forms-flow-review/src/components/ReorderTaskFilterModal.tsx
  forms-flow-review/src/components/TaskList/TaskFilterDropdown.tsx
Labels: Review effort 2/5

#619 FWF-4817 [feature] implemented process diagram with task history and overflow fix in analyze table
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-components/src/components/CustomComponents/BpmnDiagramView.tsx
  forms-flow-components/src/components/CustomComponents/SubmissionHistoryWithViewButton.tsx
  forms-flow-components/src/components/index.ts
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-review/src/helper/tableHelper.ts
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-theme/scss/_modal.scss
  forms-flow-theme/scss/_table.scss
  forms-flow-theme/scss/bpmn.scss
  forms-flow-theme/scss/formHistoryModal.scss
  forms-flow-theme/scss/index.scss
Labels: Review effort 3/5

#624 FWF-4861 [bugifx] fixed default header sorting in analyze submission key changed form camel case to snake case
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/reducers/analizeSubmissionReducer.ts
Labels: Review effort 2/5

#621 bugfix/fwf-4843-4663: fixed ui and permission issues in reviewer journey
  forms-flow-components/src/components/CustomComponents/AssignUser.tsx
  forms-flow-components/src/components/CustomComponents/InputDropdown.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/AttributeFilterModal/Notes.tsx
  forms-flow-review/src/components/TaskFilterModal/SaveFilterTab.tsx
  forms-flow-review/src/components/TaskList/AttributeFilterDropdown.tsx
  forms-flow-theme/scss/_card.scss
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/_table.scss
Labels: Review effort 3/5

#626 Removed useCallback from resizable table because updating value not getting inside the call back function
  forms-flow-components/src/components/CustomComponents/ResizableTable.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
Labels: Review effort 2/5

#627 FWF-4820: [BugFix] Button count down & validations updated
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/TaskFilterModal/SaveFilterTab.tsx
Labels: Review effort 3/5

#631 Release 7.0.1 to Main PR
  VERSION
  forms-flow-admin/package-lock.json
  forms-flow-admin/package.json
  forms-flow-admin/src/components/users/users.scss
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-components/src/components/CustomComponents/ImportModal.tsx
  forms-flow-integration/package.json
  forms-flow-nav/package.json
  forms-flow-nav/src/constants/constants.js
  forms-flow-nav/src/root.component.js
  forms-flow-nav/src/sidenav/Sidebar.jsx
  forms-flow-nav/src/sidenav/Sidebar.scss
  forms-flow-service/src/helpers/styleService.ts
  forms-flow-service/src/keycloak/KeycloakService.ts
  forms-flow-theme/scss/_aiAssistant.scss
  forms-flow-theme/scss/_button.scss
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/_theme.scss
  forms-flow-theme/scss/_variables.scss
  forms-flow-theme/scss/fileUpload.scss
  forms-flow-theme/scss/inputBox.scss
Labels: RELEASE SETUP PR

#637 FWF-4872:[BugFix] roles not saving in field filter fixed
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
Labels: Review effort 1/5

#634 Main 7.0.1 to develop
  forms-flow-nav/src/constants/constants.js
  forms-flow-nav/src/sidenav/Sidebar.jsx
  forms-flow-service/src/keycloak/KeycloakService.ts
  forms-flow-service/src/request/requestService.ts
  forms-flow-theme/scss/_forms.scss
Labels: Review effort 2/5

#629 FWF-4868 [bugfix] fixed task list reload when new task create through socket
  forms-flow-review/src/index.tsx
Labels: Review effort 2/5

#638 Fixed modal height
  forms-flow-components/src/components/CustomComponents/BpmnDiagramView.tsx
  forms-flow-components/src/components/CustomComponents/SubmissionHistoryWithViewButton.tsx
  forms-flow-theme/scss/bpmn.scss
  forms-flow-theme/scss/historyModal.scss
Labels: Review effort 2/5

#642 FWF-4880:[Modified] resizable assignee, assign to me label change
  forms-flow-components/src/components/CustomComponents/ResizableTable.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/TaskList/TaskList.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-review/src/helper/tableHelper.ts
  forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
  forms-flow-service/src/resourceBundles/de/resourceBundles.ts
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-service/src/resourceBundles/es/resourceBundles.ts
  forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
  forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
  forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
  forms-flow-theme/scss/_table.scss
  forms-flow-theme/scss/assignUser.scss
Labels: Review effort 3/5

#643 Modified/version changed to 7.1.0-rc
  VERSION
  forms-flow-admin/package-lock.json
  forms-flow-admin/package.json
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-integration/package.json
  forms-flow-nav/package.json
  forms-flow-review/package-lock.json
  forms-flow-review/package.json
  forms-flow-submissions/package-lock.json
  forms-flow-submissions/package.json
Labels: Review effort 1/5

#636 FWF-4820: [Modified] Private update modal, notes criteria
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFilterModal.tsx
  forms-flow-review/src/components/AttributeFilterModal/Notes.tsx
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModal.tsx
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
Labels: Review effort 3/5
