Repository AOT-Technologies/forms-flow-ai-micro-front-ends, pull requests merged in 2025-07, with the labels that each got.

#661 FWF-4909:[Feature] - Admin Dashboard Scroll
  forms-flow-admin/src/components/dashboard/insightDashboard.scss
  forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
  forms-flow-service/src/resourceBundles/de/resourceBundles.ts
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-service/src/resourceBundles/es/resourceBundles.ts
  forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
  forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
  forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Labels: Review effort 2/5

#663 ui fix for users with only view filter and view task fix
  forms-flow-theme/scss/assignUser.scss
Labels: Review effort 1/5

#664 🚀 Develop to Release 7.1.0
  forms-flow-admin/src/components/dashboard/insightDashboard.scss
  forms-flow-components/src/components/CustomComponents/AssignUser.tsx
  forms-flow-components/src/components/CustomComponents/DateFilter.tsx
  forms-flow-review/src/components/Assigne/Assigne.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFilterModal.tsx
  forms-flow-review/src/components/AttributeFilterModal/Notes.tsx
  forms-flow-review/src/components/TaskFilterModal/SaveFilterTab.tsx
  forms-flow-review/src/components/TaskList/AttributeFilterDropdown.tsx
  forms-flow-review/src/components/TaskList/TaskFilterDropdown.tsx
  forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
  forms-flow-service/src/resourceBundles/de/resourceBundles.ts
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-service/src/resourceBundles/es/resourceBundles.ts
  forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
  forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
  forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
  forms-flow-theme/scss/assignUser.scss
Labels: Review effort 4/5, RELEASE SETUP PR

#656 Updated versions in packages
  forms-flow-admin/package-lock.json
  forms-flow-admin/package.json
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-integration/package.json
  forms-flow-nav/package.json
  forms-flow-review/package-lock.json
  forms-flow-review/package.json
  forms-flow-service/package.json
  forms-flow-submissions/package-lock.json
  forms-flow-submissions/package.json
  forms-flow-theme/package.json
Labels: Review effort 2/5, RELEASE SETUP PR

#670 FWF-4876: [BugFix] filters persist issue fixed
  forms-flow-review/src/components/TaskList/TaskFilterDropdown.tsx
  forms-flow-review/src/components/TaskList/TaskList.tsx
Labels: Review effort 2/5

#674 [HotFix]: Resolved task variables appending issue in columns
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
Labels: Review effort 2/5

#668 FWF-4916: [Feature] Added export pdf as microfrontend
  forms-flow-components/package-lock.json
  forms-flow-components/package.json
  forms-flow-components/src/api/config.ts
  forms-flow-components/src/api/endpoints.ts
  forms-flow-components/src/customHooks/index.ts
  forms-flow-components/src/customHooks/useDownloadFile.ts
  forms-flow-components/src/declarations.d.ts
  forms-flow-components/src/formsflow-components.ts
  forms-flow-components/src/helper/helper.js
  forms-flow-components/src/service/ExportAsPdf/downloadPdfButton.tsx
Labels: Review effort 3/5

#681 FWF-4847 [bugfix] fixed dynamic variable and static variable conflict in the value
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-review/src/helper/tableHelper.ts
Labels: Review effort 3/5

#677 FWF-4906 [fixed] prevent task fetch multiple api call trigger, and multiple info call , added signel into request httpPOSTRequestWithHAL
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/index.tsx
  forms-flow-service/src/request/requestService.ts
Labels: Review effort 3/5

#682 feature/fwf-4552-4921:added sort & datefilter in submssion
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/actions/actionConstants.ts
  forms-flow-submissions/src/actions/analyzeSubmissionActions.ts
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
  forms-flow-submissions/src/declarations.d.ts
  forms-flow-submissions/src/helper/helper.ts
  forms-flow-submissions/src/reducers/analizeSubmissionReducer.ts
Labels: Review effort 3/5

#678 task variables issue fix
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
Labels: Review effort 3/5

#690 FWF-4958:[Bugfix] - Added classes to handle custom header and wizardforms in MF
  forms-flow-theme/scss/_variables.scss
Labels: Review effort 2/5

#695 FWF-4983:[HoteFix] - Task Header hidign issue in task details page.
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-theme/scss/_card.scss
Labels: Review effort 2/5

#698 FWF-4983:[HotFix] - Task Header hidign issue in task details page.
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-theme/scss/_card.scss
Labels: Review effort 2/5, Do not merge X

#697 FWF-4973: [BugFix] hide filter with same name issue fixed
  forms-flow-components/src/components/CustomComponents/DragandDropSort.tsx
Labels: Review effort 2/5

#701 FWF-4911:[Feature] - Analyze Submission Details page in MF
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/actions/actionConstants.ts
  forms-flow-submissions/src/actions/applicationActions.ts
  forms-flow-submissions/src/actions/applicationHistoryActions.ts
  forms-flow-submissions/src/actions/processActions.ts
  forms-flow-submissions/src/api/config.ts
  forms-flow-submissions/src/api/endpoints.ts
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
  forms-flow-submissions/src/components/AnalyzeSubmissionView.tsx
  forms-flow-submissions/src/components/NotFound.tsx
  forms-flow-submissions/src/components/View.tsx
  forms-flow-submissions/src/constants/constants.ts
  forms-flow-submissions/src/constants/permissions.ts
  forms-flow-submissions/src/declarations.d.ts
  forms-flow-submissions/src/formsflow-submissions.tsx
  forms-flow-submissions/src/helper/helper.ts
  forms-flow-submissions/src/index.tsx
  forms-flow-submissions/src/reducers/applicationReducer.ts
  forms-flow-submissions/src/reducers/customSubmissionReducer.ts
  forms-flow-submissions/src/reducers/index.ts
  forms-flow-submissions/src/reducers/processReducer.ts
  forms-flow-submissions/src/reducers/taskAppHistoryReducer.ts
  forms-flow-submissions/src/resourceBundles/i18n.js
  forms-flow-submissions/src/services/applicationServices.ts
  forms-flow-submissions/src/services/processServices.ts
Labels: Review effort 4/5

#703 feature/FWF-4991-compact-form [feature] convert to common utility fun…
  forms-flow-service/src/formsflow-services.ts
  forms-flow-service/src/helpers/compactViewFormService.ts
Labels: Review effort 2/5

#706 added null check for input fields
  forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
Labels: Review effort 2/5

#707 added null check for input fields map
  forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
Labels: Review effort 1/5

#704 FWF-4900[Bugfix]form component remounting issue fix and skeleton loader in task page
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/components/TaskForm.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
Labels: Review effort 3/5

#711 FWF-4050: [Feature] analyze submission api integration for static variables in analyze --> submission
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/actions/actionConstants.ts
  forms-flow-submissions/src/actions/analyzeSubmissionActions.ts
  forms-flow-submissions/src/api/endpoints.ts
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
  forms-flow-submissions/src/components/Modals/ManageFieldsSortModal.tsx
  forms-flow-submissions/src/reducers/analizeSubmissionReducer.ts
Labels: Review effort 3/5

#712 💫 Feature/fwf-4555: variable selection modal in submission
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
  forms-flow-components/src/components/CustomComponents/FormInput.tsx
  forms-flow-components/src/components/CustomComponents/Pills.tsx
  forms-flow-components/src/components/CustomComponents/VariableModal.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/api/config.ts
  forms-flow-submissions/src/api/endpoints.ts
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
  forms-flow-submissions/src/components/Modals/ManageFieldsSortModal.tsx
  forms-flow-submissions/src/declarations.d.ts
  forms-flow-theme/scss/_modal.scss
  forms-flow-theme/scss/external/formio.scss
Labels: Review effort 4/5

#716 bugfix/FWF-5126 [bugfix] retain unsaved filter
  forms-flow-review/src/components/TaskList/TaskList.tsx
Labels: Review effort 3/5

#722 FWF-4557: [Feature] Analyze submission search integration initial PR
  forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/actions/actionConstants.ts
  forms-flow-submissions/src/actions/analyzeSubmissionActions.ts
  forms-flow-submissions/src/api/endpoints.ts
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
  forms-flow-submissions/src/components/View.tsx
  forms-flow-submissions/src/reducers/analizeSubmissionReducer.ts
  forms-flow-theme/scss/collapsibleSidebar.scss
Labels: Review effort 5/5

#721 FWF-4449 [bugfix] updated error handle on image tag
  forms-flow-nav/src/root.component.js
Labels: Review effort 1/5
