Repository AOT-Technologies/forms-flow-ai-micro-front-ends, pull requests merged in 2025-08, with the labels that each got.

#723 FWF-4557: [Feature] variable key updated
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 1/5

#717 FWF-5105[bugfix]theming changes with new develop
  forms-flow-admin/src/index.scss
  forms-flow-nav/src/sidenav/Sidebar.scss
  forms-flow-nav/src/sidenav/hamburgerMenu.jsx
  forms-flow-submissions/src/index.scss
  forms-flow-theme/scss/_button.scss
  forms-flow-theme/scss/_card.scss
  forms-flow-theme/scss/_layout.scss
  forms-flow-theme/scss/_table.scss
  forms-flow-theme/scss/_theme.scss
Labels: Review effort 3/5

#720 FWF-4988:[Bugfix] - Updated classes to fix header visibility issue MF
  forms-flow-review/src/index.tsx
  forms-flow-submissions/src/components/View.tsx
  forms-flow-submissions/src/index.tsx
  forms-flow-theme/scss/_variables.scss
Labels: Review effort 2/5

#724 feature/fwf-4611-5116-data-persist&active/incative-scene-fixes
  forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/actions/actionConstants.ts
  forms-flow-submissions/src/actions/analyzeSubmissionActions.ts
  forms-flow-submissions/src/reducers/analizeSubmissionReducer.ts
  forms-flow-theme/scss/_modal.scss
  forms-flow-theme/scss/collapsibleSidebar.scss
Labels: Review effort 4/5

#725 FWF-5096 [bugfix] fixed style issue
  forms-flow-admin/src/components/roles/roles.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-theme/scss/_modal.scss
Labels: Review effort 2/5

#726 FWF-5094:[Bugfix] - Designer Journey bugfixes
  forms-flow-admin/src/components/roles/permissionTree.tsx
  forms-flow-components/src/components/CustomComponents/FormInput.tsx
  forms-flow-theme/scss/_card.scss
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/_table.scss
Labels: Review effort 2/5

#731 FWF-4557 : [Feature] Analyze submission full api integration
  forms-flow-components/src/components/CustomComponents/DragandDropSort.tsx
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
  forms-flow-submissions/src/components/Modals/ManageFieldsSortModal.tsx
Labels: Review effort 4/5

#732 FWF-5097:[bugfix] - analyze submission page ui fixes
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-components/src/service/ExportAsPdf/downloadPdfButton.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-theme/scss/_theme.scss
  forms-flow-theme/scss/bpmn.scss
Labels: Review effort 3/5

#733 FWF-4988:[Bugfix] - Header issue - Updated the container height with…
  forms-flow-theme/scss/_variables.scss
Labels: Review effort 1/5

#734 fixed noted style issues in analyse submissions
  forms-flow-components/src/components/CustomComponents/ButtonDropdown.tsx
  forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
  forms-flow-theme/scss/collapsibleSidebar.scss
Labels: Review effort 2/5

#736 FWF-4900 [Bugfix] Assignee setting added when socket update call happens when user is in task details page
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-review/src/index.tsx
Labels: Review effort 2/5

#737 feature/fwf-5136:Allowed view in disabled state of variable modal
  forms-flow-components/src/components/CustomComponents/FormInput.tsx
  forms-flow-components/src/components/CustomComponents/Tabs.tsx
  forms-flow-components/src/components/CustomComponents/VariableModal.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-theme/scss/_button.scss
  forms-flow-theme/scss/_modal.scss
Labels: Review effort 3/5

#739 FWF-5138 : [BugFix] Resolved bugs of analyze submissions
  forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
  forms-flow-components/src/components/CustomComponents/FormInput.tsx
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 3/5

#742 bugfix/fwf-5139:Fixed styles issues in variables selection modal
  forms-flow-components/src/components/CustomComponents/FormComponent.tsx
  forms-flow-submissions/src/index.scss
  forms-flow-theme/scss/external/formio.scss
Labels: Review effort 1/5

#741 FWF-5138 : [BugFix] filter persist issue fixe, active filter fix
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 2/5

#743 FWF-5138 : [BugFix] Fixed search issue with another page
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
Labels: Review effort 2/5

#745 FWF-5138 : [BugFix] Fixed panel width issue, fields not persisting issue
  forms-flow-submissions/src/Routes/SubmissionListing.tsx
  forms-flow-theme/scss/collapsibleSidebar.scss
Labels: Review effort 2/5

#746 [modified]fwf-5150: updated query param for all form listing in submission
  forms-flow-submissions/src/api/queryServices/analyzeSubmissionServices.ts
Labels: Review effort 1/5

#744 FWF-4988:[Feature] - Custom header adjustment for vizard forms
  forms-flow-theme/scss/_forms.scss
Labels: Review effort 2/5

#755 FWF-5173":[Feature] - Updated the Publish-Unpublish Modal text.
  forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
  forms-flow-service/src/resourceBundles/de/resourceBundles.ts
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-service/src/resourceBundles/es/resourceBundles.ts
  forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
  forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
  forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Labels: Review effort 2/5

#757 FWF-5137 : [Feature] Fixed date & time issue in taskList table
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
Labels: Review effort 2/5

#777 FWF-5103/style changes for ee
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-service/src/constants/constants.ts
  forms-flow-theme/scss/_modal.scss
  forms-flow-theme/scss/_table.scss
Labels: Review effort 2/5

#775 bugfix/FWF-4493 [bugfix] note rendering for bundle forms
  forms-flow-components/src/components/CustomComponents/CollapsibleSearch.tsx
  forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
  forms-flow-service/src/resourceBundles/de/resourceBundles.ts
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-service/src/resourceBundles/es/resourceBundles.ts
  forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
  forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
  forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Labels: Review effort 2/5
