Repository AOT-Technologies/forms-flow-ai-micro-front-ends, pull requests merged in 2025-05, with the labels that each got.

#557 bugfix/fwf-4534:Updated header panel bg color
  forms-flow-theme/scss/_card.scss
Labels: Review effort 1/5

#555 bugfix/fwf-4591:Fixed UI issues with reviewer journey
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-review/src/components/FormSelectionModal.tsx
  forms-flow-review/src/components/ResizableTable/ResizableTable.tsx
  forms-flow-review/src/components/TaskFilterModal.tsx
  forms-flow-theme/scss/_button.scss
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/_modal.scss
  forms-flow-theme/scss/_table.scss
  forms-flow-theme/scss/_variables.scss
  forms-flow-theme/scss/customDateRangePicker.scss
Labels: Review effort 3/5

#560 added reusable custom hook
  forms-flow-components/src/components/index.ts
  forms-flow-components/src/customHooks/index.ts
  forms-flow-components/src/customHooks/useSuccessCountdown.ts
  forms-flow-components/src/formsflow-components.ts
  forms-flow-review/src/components/TaskFilterModal.tsx
  forms-flow-review/src/declarations.d.ts
  forms-flow-theme/scss/_button.scss
Labels: Review effort 3/5

#552 FWF-4596: [Bugfix] fixed listing issue
  forms-flow-components/src/components/CustomComponents/DateFilter.tsx
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/taskActions.ts
  forms-flow-review/src/api/endpoints.ts
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/components/ResizableTable/ResizableTable.tsx
  forms-flow-review/src/components/TaskFilterModal.tsx
  forms-flow-review/src/components/constants/taskConstants.ts
  forms-flow-review/src/helper/helper.js
  forms-flow-review/src/reducers/taskReducer.ts
  forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
  forms-flow-service/src/resourceBundles/de/resourceBundles.ts
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-service/src/resourceBundles/es/resourceBundles.ts
  forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
  forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
  forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
  forms-flow-theme/scss/customDateRangePicker.scss
Labels: Review effort 4/5

#556 Fwf 4463 task filter update delete
  forms-flow-components/src/__test__/confirmModal.test.tsx
  forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx
  forms-flow-components/src/components/CustomComponents/HistoryModal.tsx
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/components/AttributeFilterModal.tsx
  forms-flow-review/src/components/ResizableTable/ResizableTable.tsx
  forms-flow-review/src/components/TaskFilterModal.tsx
  forms-flow-review/src/declarations.d.ts
  forms-flow-review/src/types/taskFilter.ts
  forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
  forms-flow-service/src/resourceBundles/de/resourceBundles.ts
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-service/src/resourceBundles/es/resourceBundles.ts
  forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
  forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
  forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Labels: Review effort 4/5

#561 FWF-4400 [added] added persist Task list data
  forms-flow-nav/src/sidenav/Sidebar.jsx
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/taskActions.ts
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/components/AttributeFilterModal.tsx
  forms-flow-review/src/components/ResizableTable/ResizableTable.tsx
  forms-flow-review/src/components/TaskFilterModal.tsx
  forms-flow-review/src/reducers/taskReducer.ts
  forms-flow-review/src/root.component.tsx
  forms-flow-service/src/storage/storageService.ts
Labels: Review effort 3/5

#565 Feature/fwf 4406 assign user
  forms-flow-components/src/components/CustomComponents/AssignUser.tsx
  forms-flow-components/src/components/CustomComponents/FormInput.tsx
  forms-flow-components/src/components/CustomComponents/InputDropdown.tsx
  forms-flow-components/src/components/index.ts
  forms-flow-components/src/declarations.d.ts
  forms-flow-review/src/Routes/TaskListing.tsx
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/taskActions.ts
  forms-flow-review/src/api/endpoints.ts
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/api/services/formatterService.ts
  forms-flow-review/src/components/ResizableTable/ResizableTable.tsx
  forms-flow-review/src/declarations.d.ts
  forms-flow-review/src/helper/helper.js
  forms-flow-review/src/reducers/taskReducer.ts
  forms-flow-theme/scss/_table.scss
  forms-flow-theme/scss/assignUser.scss
  forms-flow-theme/scss/index.scss
  forms-flow-theme/scss/inputBox.scss
Labels: Review effort 4/5

#564 FWF-4398:[Feature] - Task Details flow
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/roleActions.ts
  forms-flow-review/src/actions/taskActions.ts
  forms-flow-review/src/actions/tenantActions.ts
  forms-flow-review/src/api/config.ts
  forms-flow-review/src/api/endpoints.ts
  forms-flow-review/src/api/services/bpmTaskServices.ts
  forms-flow-review/src/api/services/formatterService.ts
  forms-flow-review/src/api/services/userSrvices.ts
  forms-flow-review/src/components/TaskForm.tsx
  forms-flow-review/src/constants/index.ts
  forms-flow-review/src/declarations.d.ts
  forms-flow-review/src/formsflow-review.tsx
  forms-flow-review/src/helper/access.js
  forms-flow-review/src/helper/helper.js
  forms-flow-review/src/helper/user.js
  forms-flow-review/src/index.tsx
  forms-flow-review/src/reducers/customSubmissionReducer.ts
  forms-flow-review/src/reducers/index.ts
  forms-flow-review/src/reducers/initialDetailReducer.ts
  forms-flow-review/src/reducers/taskReducer.ts
  forms-flow-review/src/reducers/tenantReducer.ts
  forms-flow-review/src/resourceBundles/i18n.js
  forms-flow-theme/scss/_variables.scss
Labels: Review effort 4/5

#567 FWF-4398:[Feature] - Fixed Build Failure
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/taskActions.ts
Labels: Review effort 2/5

#568 FWF-4398:[Feature] - Updated Package.json
  forms-flow-review/package-lock.json
  forms-flow-review/package.json
Labels: Review effort 2/5

#566 feature/FWF-4553 [feature] fix for reusable table
  forms-flow-components/src/components/CustomComponents/ResizableTable.tsx
  forms-flow-components/src/components/index.ts
  forms-flow-review/src/components/ResizableTable/ResizableTable.tsx
  forms-flow-review/src/declarations.d.ts
  forms-flow-review/src/index.tsx
Labels: Review effort 5/5

#573 include assigned task set always true
  forms-flow-review/src/components/TaskFilterModal.tsx
Labels: Review effort 1/5

#571 FWF-4605:[Feature] - Task Submission History in task details page.
  forms-flow-review/src/Routes/TaskDetails.tsx
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/taskActions.ts
  forms-flow-review/src/api/endpoints.ts
  forms-flow-review/src/api/services/bpmTaskServices.ts
  forms-flow-review/src/api/services/formatterService.ts
  forms-flow-review/src/components/TaskHistory.tsx
  forms-flow-review/src/reducers/taskReducer.ts
Labels: Review effort 3/5

#575 Fwf 4457/filter validations
  forms-flow-review/src/components/AttributeFilterModal.tsx
  forms-flow-review/src/components/TaskFilterModal.tsx
  forms-flow-review/src/declarations.d.ts
  forms-flow-service/src/resourceBundles/bg/resourceBundles.ts
  forms-flow-service/src/resourceBundles/de/resourceBundles.ts
  forms-flow-service/src/resourceBundles/en/resourceBundles.ts
  forms-flow-service/src/resourceBundles/es/resourceBundles.ts
  forms-flow-service/src/resourceBundles/fr/resourceBundles.ts
  forms-flow-service/src/resourceBundles/pt/resourceBundles.ts
  forms-flow-service/src/resourceBundles/zh/resourceBundles.ts
Labels: Review effort 3/5

#569 Feature/fwf 4607 4619 reorder task filter modal && shared icons
  forms-flow-components/src/components/CustomComponents/ButtonDropdown.tsx
  forms-flow-components/src/components/CustomComponents/DragandDropSort.tsx
  forms-flow-components/src/components/SvgIcons/index.tsx
  forms-flow-review/package-lock.json
  forms-flow-review/package.json
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/taskActions.ts
  forms-flow-review/src/api/endpoints.ts
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/components/ReorderTaskFilterModal.tsx
  forms-flow-review/src/components/ResizableTable/ResizableTable.tsx
  forms-flow-review/src/components/TaskFilterModal.tsx
  forms-flow-review/src/declarations.d.ts
  forms-flow-review/src/reducers/taskReducer.ts
  forms-flow-theme/scss/_button.scss
  forms-flow-theme/scss/_forms.scss
  forms-flow-theme/scss/_modal.scss
  forms-flow-theme/scss/_table.scss
  forms-flow-theme/scss/_variables.scss
Labels: Review effort 4/5

#577 minor bugfix
  forms-flow-components/src/components/CustomComponents/ConfirmModal.tsx
  forms-flow-components/src/components/SvgIcons/index.tsx
Labels: Review effort 2/5

#578 Rework : reviewer journey
  forms-flow-components/src/components/CustomComponents/DragandDropSort.tsx
  forms-flow-components/src/components/CustomComponents/ResizableTable.tsx
  forms-flow-components/src/components/CustomComponents/Tabs.tsx
  forms-flow-review/package-lock.json
  forms-flow-review/package.json
  forms-flow-review/src/Routes/TaskListing.tsx
  forms-flow-review/src/actions/actionConstants.ts
  forms-flow-review/src/actions/taskActions.ts
  forms-flow-review/src/api/endpoints.ts
  forms-flow-review/src/api/services/filterServices.ts
  forms-flow-review/src/components/Assigne/Assigne.tsx
  forms-flow-review/src/components/AttributeFilterModal.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFIlterModalBody.tsx
  forms-flow-review/src/components/AttributeFilterModal/AttributeFilterModal.tsx
  forms-flow-review/src/components/AttributeFilterModal/Notes.tsx
  forms-flow-review/src/components/AttributeFilterModal/ParametersTab.tsx
  forms-flow-review/src/components/FormSelectionModal.tsx
  forms-flow-review/src/components/ReorderTaskFilterModal.tsx
  forms-flow-review/src/components/ResizableTable/ResizableTable.tsx
  forms-flow-review/src/components/TaskFilterModal.tsx
  forms-flow-review/src/components/TaskFilterModal/ParametersTab.tsx
  forms-flow-review/src/components/TaskFilterModal/SaveFilterTab.tsx
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModal.tsx
  forms-flow-review/src/components/TaskFilterModal/TaskFilterModalBody.tsx
  forms-flow-review/src/components/TaskList/AttributeFilterDropdown.tsx
  forms-flow-review/src/components/TaskList/TaskFilterDropdown.tsx
  forms-flow-review/src/components/TaskList/TaskList.tsx
  forms-flow-review/src/components/TaskList/TasklistTable.tsx
  forms-flow-review/src/components/index.ts
  forms-flow-review/src/constants/defaultTaskVariable.ts
  forms-flow-review/src/helper/helper.js
  forms-flow-review/src/helper/permissions.ts
  forms-flow-review/src/helper/tableHelper.ts
  forms-flow-review/src/helper/taskHelper.ts
  forms-flow-review/src/reducers/taskReducer.ts
  forms-flow-review/src/root.component.tsx
  forms-flow-review/src/types/taskFilter.ts
  forms-flow-review/src/types/task_filter_variables.ts
Labels: Review effort 4/5
